#
# buildspec.yml
#

version: 0.2

#env:
#  variables:
#    name: value

phases:
#  install:
#    commands:
#      - echo CONTAINER_REGISTRY = [$CONTAINER_REGISTRY]
#      - echo CONTAINER_IMAGE = [$CONTAINER_IMAGE]
  pre_build:
    commands:
      - echo logging in to AWS ECR
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - echo converting build start time to human-readable version number
      - BUILD_VERSION=$(date --date="@$(echo $CODEBUILD_START_TIME | cut -c1-10)" +"%Y%m%d%H%M%S")
  build:
    commands:
      - echo build image on `date`
      - docker build -f package/Dockerfile -t $CONTAINER_IMAGE:latest --build-arg BUILD_TAG=$BUILD_VERSION .
      - docker tag $CONTAINER_IMAGE:latest $CONTAINER_REGISTRY/$CONTAINER_IMAGE:latest
      - docker tag $CONTAINER_IMAGE:latest $CONTAINER_REGISTRY/$CONTAINER_IMAGE:build-$BUILD_VERSION
  post_build:
    commands:
      - echo build image complete `date`
      - echo push latest image to ECR
      - docker push $CONTAINER_REGISTRY/$CONTAINER_IMAGE:latest
      - docker push $CONTAINER_REGISTRY/$CONTAINER_IMAGE:build-$BUILD_VERSION
      - aws --region=$AWS_REGION ssm put-parameter --name /containers/$CONTAINER_IMAGE/latest --value build-$BUILD_VERSION --type String --overwrite

#
# end of file
#
