BEGIN;
ALTER TABLE bookmarks ADD source_id integer NOT NULL REFERENCES sources(id) ON DELETE CASCADE DEFAULT 1;
ALTER TABLE bookmarks ADD added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
COMMIT;